### ISSUE TITLE
강의

### ISSUE THREAD

**Issue by gimhanul** [jjarappappa/icecream#16]
### ✨ Describe

강의 관련 api를 만들어야 합니다

### ✅ Tasks

- [x] lecture entity, repository
- [x] 강의 만들기
- [x] 강의 수정
- [x] 삭제
- [x] 조회
- [x] 상세조회
- [x] 수강 신청
- [x] 수강 신청 취소
- [x] 강의 참가자 조회
